export const translations = {
    ru: {
        title: 'Список дел',
        capture: 'Создать новую задачу',
        modalCapture: 'Редактировать задачу',
        inputPlaceholderTask: 'Введите новую задачу...',
        inputPlaceholderSearch: 'Поиск задачи',
        btnCancel: 'Отмена',
        btnSave: 'Сохранить',
        btnAllTasks: 'Все задачи',
        btnClearAll: 'Удалить задачи',
        btnLabel: 'Удалить задачу',
        btnArchived: 'В архив',
        filtersAll: 'Все',
        filterCompleted: 'Завершенные',
        filterUncompleted: 'Незавершенные',
        filterArchived: 'Архив',
        ariaDelete: 'Убрать отметку важности',
        ariaImportant: 'Отметить задачу как важную',
        titleSuccess: 'Ты супер!',
        textSuccess: 'Все задачи выполнены, можно ехать на море!',
        btnSuccess: 'Ура! За билетами!',
        btnLang: 'Ру',
        plug: 'Пока нет ни одной задачи...'
    },
    en: {
        title: 'To-Do List',
        capture: 'Create a new task',
        modalCapture: 'Edit a task',
        inputPlaceholderTask: 'Enter new task...',
        inputPlaceholderSearch: 'Search task...',
        btnCancel: 'Cancel',
        btnSave: 'Save',
        btnAllTasks: 'All tasks',
        btnClearAll: 'Delete tasks',
        btnLabel: 'Delete task',
        btnArchived: 'To archive',
        filtersAll: 'All',
        filterCompleted: 'Completed',
        filterUncompleted: 'Uncompleted',
        filterArchived: 'Archive',
        ariaDelete: 'Delete mark important',
        ariaImportant: 'Mark task important',
        titleSuccess: 'You are super!',
        textSuccess: 'All tasks are done, you can relax!',
        btnSuccess: 'Hooray! Off to buy tickets!',
        btnLang: 'En',
        plug: 'There are no tasks yet...'
    }
}
